### ISSUE TITLE
Doesn't Work With Fixed Layouts

### ISSUE THREAD

**Issue by jmonday** [jney/jquery.pageless#1]
I am using a fixed layout so my navigation menu is always visible on the left side of the page. My content then scrolls as normal. With this setup, this plugin does not work correctly.

Long story short... 'distance' will never be zero, so the call is never made for additional data. $(window).scrollTop() will always be zero, even if you are at the bottom of the page.

More details using Firebug console:
    $(document).height()
    => 1176

```
$(window).scrollTop()
=> 0

distance
=> 952

$.pageless.settings.distance
=> 100

(distance < $.pageless.settings.distance)
=> false
```

When CSS is disabled, the call is made.

**Comment by jney** [comment]
sorry for late answer. i'm not really sure i understand. you mean that the scrolled element is not window element ? do you have any example to check it ?

**Comment by pelcasandra** [comment]
It happens to me too. Problem is when using iScroll (for fixed positioning in Mobile Safari) plus jQuery.pageless.

On the page i got something like

https://gist.github.com/809314

Problem is that pagination will try to catch also the id wrapper and the container, adding again a new wrapper, continaer and results inside the previous #results div casuing an overlapping.

**Comment by jney** [comment]
hi pelcito, it's hard to read your comment formating is really weird.
have you set `#wrapper` as the container ?

**Comment by pelcasandra** [comment]
https://gist.github.com/809314

There it is. There's #wrapper, then there's a #container and then there's #results.

**Comment by pelcasandra** [comment]
Check here
http://cubiq.org/iscroll

**Comment by jney** [comment]
can i see how you're calling pageless ?

**Comment by pelcasandra** [comment]
Sure, here
https://gist.github.com/809375

**Comment by jney** [comment]
try to call it like this :

```
<%= pageless(@attachments.total_pages, attachments_path, "#container") %>
```

**Comment by pelcasandra** [comment]
It still remains the same. 

I don't fully understand why is adding the whole page inside the current div.

**Comment by jney** [comment]
can i have an access to your app ?

**Comment by jney** [comment]
i made a fix to your app, can you check ? it looks like a rails problem, not a plugin one. because the ajax response contains the whole page with layout

**Comment by pelcasandra** [comment]
Problem solved. I change the action name updates to index and the collection then came okay.

Not a jQuery.pageless plugin issue.

Thank you for you time jney!
