### ISSUE TITLE
Turbolinks support??

### ISSUE THREAD

**Issue by licatajustin** [jney/jquery.pageless#26]
Currently in a rails 4 app it works as it should unless you are running Turbolinks. If you run Turbolinks, then it renders as the typical will_paginate pagination links.

**Comment by amenzhinsky** [comment]
Can anybody check my commit https://github.com/amenzhinsky/jquery.pageless/commit/8f7797be3a29612f5aad703b803bef7416fa576a

If it's ok I'll open a pull request

**Comment by licatajustin** [comment]
Looks good to me and works in a Rails 4 app using turbolinks.

**Comment by jney** [comment]
sounds good to me.
@amenzhinsky you can open a pull request.
thank you both.
