### ISSUE TITLE
Scroll on container doesn't behave properly

### ISSUE THREAD

**Issue by tyok** [jney/jquery.pageless#3]
Hi, I encountered a bug that occured using these steps:
1. Design a `div` to use `overflow: scroll` so we can scroll on it.
2. Set pageless to use that `div` as container (e.g `$(x).pageless({container: x})`).
3. Load all the javascript (jquery.pageless.js and the code above) in the body, not head. 

Buggy behavior:
1. Scroll on the div. The pageless script doesn't work.
2. Scroll on body. The pageless script works.

Wanted behavior:
Scroll on the div. The pageless script works and loads the next page.

The fix is really simple, just add this line below [here](https://github.com/jney/jquery.pageless/blob/master/lib/jquery.pageless.js#L88); in `init` function:
    if (settings.container) container = settings.container;

**Comment by jney** [comment]
you're right container was set too early. fixed now. thank you and sorry answering you so late
